### ISSUE TITLE
Script crashes at 1%

### ISSUE THREAD

**Issue by yurividal** [Greegko/google-metadata-matcher#2]
```` 

python3 merge_metadata.py /mnt/DISK2/Takeout/GooglePhotos /mnt/DISK2/googlephotos_fixed/

Total images found: 35331
Traceback (most recent call last):--------------------------------------------------------------------| 0.1% 
  File "/home/yurividal/google-metadata-matcher/src/merge_metadata.py", line 26, in <module>
    processFolder(args.source_folder, args.edited_word, args.optimize, args.output_folder, args.max_dimension)
  File "/home/yurividal/google-metadata-matcher/src/process_folder.py", line 65, in processFolder
    orientation = image_exif[OrientationTagID]
  File "/home/yurividal/.local/lib/python3.10/site-packages/PIL/Image.py", line 3859, in __getitem__
    return self._data[tag]
KeyError: 274
````

Any ideas what could be happening here?

**Comment by Greegko** [comment]
It seems maybe this image don't have metadata somehow. Can you provide this image as example ?

**Comment by Greegko** [comment]
I have fixed the issue, I could reproduce with a new export.
