### ISSUE TITLE
Issue with some files "ValueError: "dump" got wrong type of exif value. 37500 in Exif IFD. Got as <class 'tuple'>"

### ISSUE THREAD

**Issue by Mottysc** [Greegko/google-metadata-matcher#5]
I'm not sure why I'm getting this error when I run the code. What helps is if I find the file in question and then "resize" the file (but putting 100% in the dimensions so I'm not actually resizing it).

```
Traceback (most recent call last):
  File "[python]\lib\site-packages\piexif\_dump.py", line 267, in _value_to_bytes
    four_bytes_over = b"" + raw_value
TypeError: can't concat tuple to bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[python]\lib\site-packages\piexif\_dump.py", line 335, in _dict_to_bytes
    length_str, value_str, four_bytes_over = _value_to_bytes(raw_value,
  File "[python]\lib\site-packages\piexif\_dump.py", line 269, in _value_to_bytes
    raise ValueError("Got invalid type to convert.")
ValueError: Got invalid type to convert.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Photos\google-metadata-matcher-master\google-metadata-matcher-master\src\merge_metadata.py", line 26, in <module>
    processFolder(args.source_folder, args.edited_word, args.optimize, args.output_folder, args.max_dimension)
  File "D:\Photos\google-metadata-matcher-master\google-metadata-matcher-master\src\process_folder.py", line 96, in processFolder
    new_exif = adjust_exif(image.info["exif"], metadata)
  File "D:\Photos\google-metadata-matcher-master\google-metadata-matcher-master\src\auxFunctions.py", line 135, in adjust_exif
    return piexif.dump(exif_dict)
  File "[python]\lib\site-packages\piexif\_dump.py", line 68, in dump
    exif_set = _dict_to_bytes(exif_ifd, "Exif", zeroth_length)
  File "[python]\lib\site-packages\piexif\_dump.py", line 339, in _dict_to_bytes
    raise ValueError(
ValueError: "dump" got wrong type of exif value.
37500 in Exif IFD. Got as <class 'tuple'>.
```

**Comment by Pandananana** [comment]
I have the same issue

**Comment by PapyrusNotes** [comment]
The key value 37500 of exif_dict is area of 'Makernote'.
The image's EXIF data you handle seems to have this area.
My version of pyexif is 1.1.3.

Clear 'Makernote' area before processing the image.

```python3
if piexif.ExifIFD.MakerNote in exif_dict["Exif"]:
    exif_dict["Exif"][piexif.ExifIFD.MakerNote] = b""

```
